# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - ./manchester-db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${DOCKER_MYSQL_PORT}
